server:
  port: 9001
  # Enable response compression
#  compression:
#    enabled: true
#    # The comma-separated list of mime types that should be compressed
#    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json,application/pdf
#    # Compress the response only if the response size is at least 1KB
#    min-response-size: 1024


spring:
  profiles:
    active: default
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect:  org.hibernate.dialect.MySQL5Dialect
        show_sql: true
        use_sql_comments: true
        format_sql: true
        type: trace

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/merge_toc?useTimezone=true&serverTimezone=UTC
    username: root
    password: root
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB
